//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.04 at 06:30:39 PM MSK 
//


package com.le.emu.mmba.transfer_order;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.le.emu.mmba.transfer_order package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.le.emu.mmba.transfer_order
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Request.Data }
     * 
     */
    public Request.Data createRequestData() {
        return new Request.Data();
    }

    /**
     * Create an instance of {@link Request.Head }
     * 
     */
    public Request.Head createRequestHead() {
        return new Request.Head();
    }

    /**
     * Create an instance of {@link Request.Data.Account }
     * 
     */
    public Request.Data.Account createRequestDataAccount() {
        return new Request.Data.Account();
    }

}
