//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.04 at 06:30:39 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.mmba.emu.le.com/transfer_order", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.le.emu.mmba.transfer_order;
