//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.04 at 06:30:39 PM MSK 
//


package com.le.emu.mmba.transfer_order;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Head"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DateCreate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                   &lt;element name="ProcessID" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
 *                   &lt;element name="Service" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
 *                   &lt;element name="ServOperation" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Data"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element name="DisposeType"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="MONEY_REDISTRIBUTION_REMOTELY"/&gt;
 *                         &lt;enumeration value="MONEY_REDISTRIBUTION_REMOTELY_KUA"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="GKK" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="OrderSourceSystem" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
 *                   &lt;element name="SourceSystemOrderId" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
 *                   &lt;element name="AgreementNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="AgreementType"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="BrokerContract"/&gt;
 *                         &lt;enumeration value="IndividualContract"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="SourceDiasoftCode" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
 *                   &lt;element name="DestinationDiasoftCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SourcePlace" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="DestinationPlace" type="{http://www.mmba.emu.le.com/transfer_order}StIntOrEmpty" minOccurs="0"/&gt;
 *                   &lt;element name="Ammount" type="{http://www.mmba.emu.le.com/transfer_order}StDecimalOrEmpty" minOccurs="0"/&gt;
 *                   &lt;element name="Currency" type="{http://www.mmba.emu.le.com/transfer_order}StCurrencyCode"/&gt;
 *                   &lt;element name="IsAll" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                   &lt;element name="Account" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="WithdrawalType"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                 &lt;enumeration value="1"/&gt;
 *                                 &lt;enumeration value="2"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="Account" type="{http://www.mmba.emu.le.com/transfer_order}StAccount408" /&gt;
 *                           &lt;attribute name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="BankName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="BIK" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="SWIFT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="CorAccount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="ITMSWIFT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="ITMName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="ITMAccount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="PaymentDetails" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "data"
})
@XmlRootElement(name = "Request")
public class Request {

    @XmlElement(name = "Head", required = true)
    protected Request.Head head;
    @XmlElement(name = "Data", required = true)
    protected Request.Data data;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link Request.Head }
     *     
     */
    public Request.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request.Head }
     *     
     */
    public void setHead(Request.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Request.Data }
     *     
     */
    public Request.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request.Data }
     *     
     */
    public void setData(Request.Data value) {
        this.data = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element name="DisposeType"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="MONEY_REDISTRIBUTION_REMOTELY"/&gt;
     *               &lt;enumeration value="MONEY_REDISTRIBUTION_REMOTELY_KUA"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="GKK" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="OrderSourceSystem" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
     *         &lt;element name="SourceSystemOrderId" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
     *         &lt;element name="AgreementNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="AgreementType"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="BrokerContract"/&gt;
     *               &lt;enumeration value="IndividualContract"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="SourceDiasoftCode" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
     *         &lt;element name="DestinationDiasoftCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SourcePlace" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="DestinationPlace" type="{http://www.mmba.emu.le.com/transfer_order}StIntOrEmpty" minOccurs="0"/&gt;
     *         &lt;element name="Ammount" type="{http://www.mmba.emu.le.com/transfer_order}StDecimalOrEmpty" minOccurs="0"/&gt;
     *         &lt;element name="Currency" type="{http://www.mmba.emu.le.com/transfer_order}StCurrencyCode"/&gt;
     *         &lt;element name="IsAll" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *         &lt;element name="Account" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="WithdrawalType"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                       &lt;enumeration value="1"/&gt;
     *                       &lt;enumeration value="2"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="Account" type="{http://www.mmba.emu.le.com/transfer_order}StAccount408" /&gt;
     *                 &lt;attribute name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="BankName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="BIK" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="SWIFT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="CorAccount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="ITMSWIFT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="ITMName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="ITMAccount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="PaymentDetails" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Data {

        @XmlElement(name = "DisposeType", required = true)
        protected String disposeType;
        @XmlElement(name = "GKK")
        protected int gkk;
        @XmlElement(name = "OrderSourceSystem", required = true)
        protected String orderSourceSystem;
        @XmlElement(name = "SourceSystemOrderId", required = true)
        protected String sourceSystemOrderId;
        @XmlElement(name = "AgreementNumber", required = true)
        protected String agreementNumber;
        @XmlElement(name = "AgreementType", required = true)
        protected String agreementType;
        @XmlElement(name = "SourceDiasoftCode", required = true)
        protected String sourceDiasoftCode;
        @XmlElement(name = "DestinationDiasoftCode")
        protected String destinationDiasoftCode;
        @XmlElement(name = "SourcePlace")
        protected int sourcePlace;
        @XmlElement(name = "DestinationPlace")
        protected String destinationPlace;
        @XmlElement(name = "Ammount")
        protected String ammount;
        @XmlElement(name = "Currency", required = true)
        protected String currency;
        @XmlElement(name = "IsAll")
        protected Boolean isAll;
        @XmlElement(name = "Account")
        protected Request.Data.Account account;

        /**
         * Gets the value of the disposeType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisposeType() {
            return disposeType;
        }

        /**
         * Sets the value of the disposeType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisposeType(String value) {
            this.disposeType = value;
        }

        /**
         * Gets the value of the gkk property.
         * 
         */
        public int getGKK() {
            return gkk;
        }

        /**
         * Sets the value of the gkk property.
         * 
         */
        public void setGKK(int value) {
            this.gkk = value;
        }

        /**
         * Gets the value of the orderSourceSystem property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderSourceSystem() {
            return orderSourceSystem;
        }

        /**
         * Sets the value of the orderSourceSystem property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderSourceSystem(String value) {
            this.orderSourceSystem = value;
        }

        /**
         * Gets the value of the sourceSystemOrderId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceSystemOrderId() {
            return sourceSystemOrderId;
        }

        /**
         * Sets the value of the sourceSystemOrderId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceSystemOrderId(String value) {
            this.sourceSystemOrderId = value;
        }

        /**
         * Gets the value of the agreementNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAgreementNumber() {
            return agreementNumber;
        }

        /**
         * Sets the value of the agreementNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAgreementNumber(String value) {
            this.agreementNumber = value;
        }

        /**
         * Gets the value of the agreementType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAgreementType() {
            return agreementType;
        }

        /**
         * Sets the value of the agreementType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAgreementType(String value) {
            this.agreementType = value;
        }

        /**
         * Gets the value of the sourceDiasoftCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceDiasoftCode() {
            return sourceDiasoftCode;
        }

        /**
         * Sets the value of the sourceDiasoftCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceDiasoftCode(String value) {
            this.sourceDiasoftCode = value;
        }

        /**
         * Gets the value of the destinationDiasoftCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinationDiasoftCode() {
            return destinationDiasoftCode;
        }

        /**
         * Sets the value of the destinationDiasoftCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinationDiasoftCode(String value) {
            this.destinationDiasoftCode = value;
        }

        /**
         * Gets the value of the sourcePlace property.
         * 
         */
        public int getSourcePlace() {
            return sourcePlace;
        }

        /**
         * Sets the value of the sourcePlace property.
         * 
         */
        public void setSourcePlace(int value) {
            this.sourcePlace = value;
        }

        /**
         * Gets the value of the destinationPlace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinationPlace() {
            return destinationPlace;
        }

        /**
         * Sets the value of the destinationPlace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinationPlace(String value) {
            this.destinationPlace = value;
        }

        /**
         * Gets the value of the ammount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmmount() {
            return ammount;
        }

        /**
         * Sets the value of the ammount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmmount(String value) {
            this.ammount = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

        /**
         * Gets the value of the isAll property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isIsAll() {
            return isAll;
        }

        /**
         * Sets the value of the isAll property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIsAll(Boolean value) {
            this.isAll = value;
        }

        /**
         * Gets the value of the account property.
         * 
         * @return
         *     possible object is
         *     {@link Request.Data.Account }
         *     
         */
        public Request.Data.Account getAccount() {
            return account;
        }

        /**
         * Sets the value of the account property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.Data.Account }
         *     
         */
        public void setAccount(Request.Data.Account value) {
            this.account = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="WithdrawalType"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *             &lt;enumeration value="1"/&gt;
         *             &lt;enumeration value="2"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="Account" type="{http://www.mmba.emu.le.com/transfer_order}StAccount408" /&gt;
         *       &lt;attribute name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="BankName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="BIK" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="SWIFT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="CorAccount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="ITMSWIFT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="ITMName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="ITMAccount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="PaymentDetails" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Account {

            @XmlAttribute(name = "WithdrawalType")
            protected Integer withdrawalType;
            @XmlAttribute(name = "Account")
            protected String account;
            @XmlAttribute(name = "Currency")
            protected String currency;
            @XmlAttribute(name = "BankName")
            protected String bankName;
            @XmlAttribute(name = "BIK")
            protected String bik;
            @XmlAttribute(name = "SWIFT")
            protected String swift;
            @XmlAttribute(name = "CorAccount")
            protected String corAccount;
            @XmlAttribute(name = "ITMSWIFT")
            protected String itmswift;
            @XmlAttribute(name = "ITMName")
            protected String itmName;
            @XmlAttribute(name = "ITMAccount")
            protected String itmAccount;
            @XmlAttribute(name = "PaymentDetails")
            protected String paymentDetails;
            @XmlAttribute(name = "Comment")
            protected String comment;

            /**
             * Gets the value of the withdrawalType property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getWithdrawalType() {
                return withdrawalType;
            }

            /**
             * Sets the value of the withdrawalType property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setWithdrawalType(Integer value) {
                this.withdrawalType = value;
            }

            /**
             * Gets the value of the account property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccount() {
                return account;
            }

            /**
             * Sets the value of the account property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccount(String value) {
                this.account = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

            /**
             * Gets the value of the bankName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBankName() {
                return bankName;
            }

            /**
             * Sets the value of the bankName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBankName(String value) {
                this.bankName = value;
            }

            /**
             * Gets the value of the bik property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBIK() {
                return bik;
            }

            /**
             * Sets the value of the bik property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBIK(String value) {
                this.bik = value;
            }

            /**
             * Gets the value of the swift property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSWIFT() {
                return swift;
            }

            /**
             * Sets the value of the swift property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSWIFT(String value) {
                this.swift = value;
            }

            /**
             * Gets the value of the corAccount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCorAccount() {
                return corAccount;
            }

            /**
             * Sets the value of the corAccount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCorAccount(String value) {
                this.corAccount = value;
            }

            /**
             * Gets the value of the itmswift property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getITMSWIFT() {
                return itmswift;
            }

            /**
             * Sets the value of the itmswift property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setITMSWIFT(String value) {
                this.itmswift = value;
            }

            /**
             * Gets the value of the itmName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getITMName() {
                return itmName;
            }

            /**
             * Sets the value of the itmName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setITMName(String value) {
                this.itmName = value;
            }

            /**
             * Gets the value of the itmAccount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getITMAccount() {
                return itmAccount;
            }

            /**
             * Sets the value of the itmAccount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setITMAccount(String value) {
                this.itmAccount = value;
            }

            /**
             * Gets the value of the paymentDetails property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPaymentDetails() {
                return paymentDetails;
            }

            /**
             * Sets the value of the paymentDetails property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPaymentDetails(String value) {
                this.paymentDetails = value;
            }

            /**
             * Gets the value of the comment property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComment() {
                return comment;
            }

            /**
             * Sets the value of the comment property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComment(String value) {
                this.comment = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DateCreate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="ProcessID" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
     *         &lt;element name="Service" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
     *         &lt;element name="ServOperation" type="{http://www.mmba.emu.le.com/transfer_order}StNotEmptyString"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dateCreate",
        "processID",
        "service",
        "servOperation"
    })
    public static class Head {

        @XmlElement(name = "DateCreate", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar dateCreate;
        @XmlElement(name = "ProcessID", required = true)
        protected String processID;
        @XmlElement(name = "Service", required = true)
        protected String service;
        @XmlElement(name = "ServOperation", required = true)
        protected String servOperation;

        /**
         * Gets the value of the dateCreate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDateCreate() {
            return dateCreate;
        }

        /**
         * Sets the value of the dateCreate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDateCreate(XMLGregorianCalendar value) {
            this.dateCreate = value;
        }

        /**
         * Gets the value of the processID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcessID() {
            return processID;
        }

        /**
         * Sets the value of the processID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessID(String value) {
            this.processID = value;
        }

        /**
         * Gets the value of the service property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getService() {
            return service;
        }

        /**
         * Sets the value of the service property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setService(String value) {
            this.service = value;
        }

        /**
         * Gets the value of the servOperation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServOperation() {
            return servOperation;
        }

        /**
         * Sets the value of the servOperation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServOperation(String value) {
            this.servOperation = value;
        }

    }

}
